version: 2

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore
    include: scope
  allow:
  - dependency-type: "development"
  ignore:
  - dependency-name: "semantic-release" # requires Node 18 starting at 20.0.0
    versions:
      - '>=20.0.0'
